medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('postgres', 'postgres@19') }}"
      password: postgres@19
      port: 5433
      dbname: medical_warehouse
      schema: public
      threads: 4
