version: 2

models:
  - name: stg_telegram_messages
    description: "Cleaned and standardized Telegram messages from raw ingestion"

    columns:
      - name: message_pk
        description: "Surrogate primary key for each Telegram message"
        tests:
          - not_null
          - unique

      - name: channel_name
        description: "Telegram channel name"
        tests:
          - not_null

      - name: message_date
        description: "Timestamp when the message was sent"

      - name: sender_id
        description: "Telegram sender ID"

      - name: message_text
        description: "Message text content"
