version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"

    columns:
      - name: channel_pk
        description: "Surrogate key for channel"
        tests:
          - not_null
          - unique

      - name: channel_name
        description: "Telegram channel name"
        tests:
          - not_null

  - name: dim_dates
    description: "Date dimension table derived from message timestamps"

    columns:
      - name: date_day
        description: "Calendar date (YYYY-MM-DD)"
        tests:
          - not_null
          - unique

  - name: fact_messages
    description: "Fact table containing Telegram messages"

    columns:
      - name: message_pk
        description: "Surrogate key for message"
        tests:
          - not_null
          - unique

      - name: channel_pk
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_pk

      - name: message_date
        description: "Timestamp of the message"
        tests:
          - not_null
